[meta]
name = "Core"
description = "SourceMod Core"
author = "AlliedModders LLC"

[source]
type = "git"
repository = "https://github.com/alliedmodders/sourcemod.git"
patterns = [
	"plugins/include/*.inc"
]
